name: Playwright tests

on:
  push:
    branches: ["next"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: yarn install

      - name: Wait for Netlify Deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: wait-netlify
        with:
          site_id: "ff6b9b65-e128-49a0-9da7-a362be70aea1"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: E2E testing
        run: yarn test --project=chromium
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.wait-netlify.outputs.url }}
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: .tests/
          retention-days: 30
