name: Playwright Tests

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  test:
    name: Creating Tests
    runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
        run: |
          yarn install
          yarn build
          yarn start
          yarn test